### ISSUE TITLE
Coding Consistency

### ISSUE THREAD

**Issue by songyang-dev** [kovek/MCSC_game#1]
So, since more people are joining on the programming part, I think that it would be beneficial that we established a notation guideline on the repository, either on the README file or a wiki page.

What I mean by notation/coding consistency is the fact that certain objects, methods, functions, variables, etc. can be written in different ways. For example, someone could type:

_class OnScreenImage(object):_

OR

_class On_Screen_Image(object):_

I know that the first one in this example is the one that we are using. However, class methods and generic variables don't have any multi-word format established yet. We should set a guideline for these objects' names so that we can easily recall classes, methods or variables later on.

Since I'm not the lead developer, I'll leave this issue to the leaders.

**Comment by henrickd** [comment]
http://en.wikipedia.org/wiki/Naming_convention_%28programming%29#Python_and_Ruby

Classes are written LikeThis. Functions are written like_this. Variables should be written like_this. Comments for everything you add. Class, function and variable names should be descriptive (no foo/bar please, idgaf if you're just testing stuff, if you push smth it must be clearly written). Classes should depend on appropriate classes (I need to work on this myself).

And sorry for commenting your code, I had to do it since it wouldn't run: required some additional arguments for every item, and I was doing some stuff that required the game to function asap. But we should definitely use it for some things (the shadow positioning, also launching projectiles is extremely annoying to offset constantly)

**Comment by songyang-dev** [comment]
thanks for the info!
